### ISSUE TITLE
Impliment get_interfaces_ip API

### ISSUE THREAD

**Issue by tlourey** [shrank/napalm_netgear#2]
Hi @shrank , 

Any chance you could impliment the `get_interfaces_ip` API with the command `show ip interface brief`? 

Trying to use nautobot device onboarding but it needs both get_facts and [`get_interfaces_ip`](https://github.com/nautobot/nautobot-app-device-onboarding/blob/f7134007ccf5d9bb12c5b106dd943ede34dd2d2c/nautobot_device_onboarding/netdev_keeper.py#L248) but since it doesn't exist its erroring out. 

I'm not experienced enough in python to submit a PR. 

Many thanks. 

Tim

**Comment by shrank** [comment]
Hi Tim 

I don't have a device available until April.

Can you post the command output and the device model? That would help to get started.

**Comment by tlourey** [comment]
Sure. I don't have a very complicated config, others might. 

```
(M4300-52G-PoE+) #show ip interface brief 

Interface    State  IP Address      IP Mask         TYPE            Method
-----------  -----  --------------- --------------- --------------- ---------------
vlan 1       Up     169.254.100.100 255.255.0.0     Primary         DHCP
vlan 13      Up     192.168.13.1    255.255.255.0   Primary         Manual
vlan 14      Up     192.168.14.1    255.255.255.0   Primary         Manual

(M4300-52G-PoE+) #
```

In some cases I have vlan 1 fully disabled. 

```
(SwitchName) #show ip interface brief 

Interface    State  IP Address      IP Mask         TYPE            Method
-----------  -----  --------------- --------------- --------------- ---------------
vlan 12      Up     192.168.12.13   255.255.255.0   Primary         Manual

(SwitchName) #
````

**Comment by shrank** [comment]
I uploaded a pre-release version for you. I was not really able to test it but it's worth a try.

You can install it like this: `pip install napalm-netgear==0.0.2a1`

**Comment by tlourey** [comment]
It worked first go with the [Nautobot Device Onboarding plugin](https://github.com/nautobot/nautobot-app-device-onboarding)! It completed successfully (Nautobot didn't learn the other IP Addresses but I think that's an issue with it).

I have **not** tried it by using the Napalm cli as I'm not 100% sure what vendor to specify and how to specify the napalm_netgear driver. If you can give me the napalm cli parameters to specify the driver and correct vendor to use, I'll give that a go too. 

Either way, I think its good to go! 

Suggest you update the readme to add `get_interfaces_ip` to the partially implemented list :)

Many many thanks!

**Comment by shrank** [comment]
The vender name should be `netgear`

somehting like: `napalm --user vagrant --password vagrant --vendor netgear  10.0.0.1 get_interfaces_ip`

**Comment by tlourey** [comment]
I'll deploy the new stable version tomorrow after it comes out on PyPI and give this a try tomorrow. Many thanks again!
